# Generated by Django 5.2.4 on 2025-07-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=200, verbose_name='Razão Social')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='Número do Pedido')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('followup_date', models.DateField(verbose_name='Data de Followup')),
                ('warehouse', models.CharField(max_length=10, verbose_name='Armazém')),
                ('items_count', models.IntegerField(verbose_name='Quantidade de Itens')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['followup_date', 'number'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(max_length=20, verbose_name='Número da Carga')),
                ('manifest_date', models.DateField(verbose_name='Data do Manifesto')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Número da Nota')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('manifest_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Manifesto')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ['-manifest_date'],
            },
        ),
    ]
