# Generated by Django 5.2.4 on 2025-07-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('name', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo')], default='ATIVO', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pc', models.CharField(max_length=20, unique=True, verbose_name='Número PC')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('quantidade_itens', models.IntegerField(verbose_name='Quantidade de Itens')),
                ('followup_date', models.DateField(verbose_name='Data de Follow-up')),
                ('armazenamento', models.CharField(max_length=5, verbose_name='Armazenamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PARCIAL', 'Parcial'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'verbose_name_plural': 'Pedidos de Compra',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo_number', models.CharField(max_length=20, verbose_name='Número da Carga')),
                ('manifest_date', models.DateField(verbose_name='Data do Manifesto')),
                ('invoice_number', models.CharField(max_length=20, verbose_name='Número da Nota')),
                ('issue_date', models.DateField(verbose_name='Data de Emissão')),
                ('manifest_time', models.TimeField(blank=True, null=True, verbose_name='Hora do Manifesto')),
                ('entry_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada')),
                ('exit_time', models.TimeField(blank=True, null=True, verbose_name='Hora de Saída')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('FINALIZADO', 'Finalizado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('purchase_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.purchaseorder', verbose_name='Pedido de Compra')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.supplier', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Recebimento',
                'verbose_name_plural': 'Recebimentos',
                'ordering': ['-manifest_date'],
            },
        ),
    ]
